### PR TITLE
Clean up this module for NPM publishing

### PR DESCRIPTION
**Pull request by dancrumb**
Removed the `main` reference in package.json
Created an appropraite .npmignore file
Fixed some errors in the documentation

### CODE REVIEW

**Comment by jeremyckahn** [comment]
Can you update this PR to properly target `develop`?  I tried changing it myself but that introduced some more commits — I think `feature/npm-friendly` needs to be rebased onto `develop`.

**Comment by dancrumb** [comment]
Done! Rebasing wasn't really necessary as I think the gap between develop and master was a fast-forward difference anyway.

**Comment by dancrumb** [comment]
TBH, those commits should be in master anyway, right?

**Comment by jeremyckahn** [comment]
@dancrumb Yeah I think you're right.  Thanks for the PR!

**Pull request merged**
